$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"

dictionaryDefinitions:
  - name: project-words
    path: .github/spellcheck/dictionaries/project-words.txt

  - name: custom-python
    path: .github/spellcheck/dictionaries/python.txt

dictionaries:
  - custom-python
  - en_US
  - project-words
  - python

ignorePaths:
  - "**/.github/spellcheck/dictionaries/**"
  - "**/*.xml*"
  - "**/*.in"
  - "**/*.sh"
  - "**/data/icons/**"
  - "**/meson.build"
