$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
globRoot: ./
dictionaryDefinitions:
  - name: project-words
    path: .github/spellcheck/dictionaries/project-words.txt
  - name: custom-python
    path: .github/spellcheck/dictionaries/python.txt
dictionaries:
  - project-words
  - python
  - en-gb
  - custom-python
ignorePaths:
  - "**/.github/spellcheck/dictionaries/**"
  - "**/*.xml*"
  - "**/*.in"
  - "**/*.sh"
  - "**/data/icons/**"
  - "**/meson.build"

