"""Contains the layouts of several common keyboard layouts based on evdev.ecodes."""

KEYBOARD_LAYOUTS = {
    "en_US": [  # US QWERTY
        [
            (1, "Esc", True),
            (59, "F1", True),
            (60, "F2", True),
            (61, "F3", True),
            (62, "F4", True),
            (63, "F5", True),
            (64, "F6", True),
            (65, "F7", True),
            (66, "F8", True),
            (67, "F9", True),
            (68, "F10", True),
            (87, "F11", True),
            (88, "F12", True),
        ],
        [
            (41, "`", False),
            (2, "1", False),
            (3, "2", False),
            (4, "3", False),
            (5, "4", False),
            (6, "5", False),
            (7, "6", False),
            (8, "7", False),
            (9, "8", False),
            (10, "9", False),
            (11, "0", False),
            (12, "-", False),
            (13, "=", False),
            (14, "Backspace", True),
        ],
        [
            (15, "Tab", True),
            (16, "Q", False),
            (17, "W", False),
            (18, "E", False),
            (19, "R", False),
            (20, "T", False),
            (21, "Y", False),
            (22, "U", False),
            (23, "I", False),
            (24, "O", False),
            (25, "P", False),
            (26, "[", False),
            (27, "]", False),
            (43, "\\", True),
        ],
        [
            (58, "Caps", True),
            (30, "A", False),
            (31, "S", False),
            (32, "D", False),
            (33, "F", False),
            (34, "G", False),
            (35, "H", False),
            (36, "J", False),
            (37, "K", False),
            (38, "L", False),
            (39, ";", False),
            (40, "'", False),
            (28, "Enter", True),
        ],
        [
            (42, "Shift", True),
            (44, "Z", False),
            (45, "X", False),
            (46, "C", False),
            (47, "V", False),
            (48, "B", False),
            (49, "N", False),
            (50, "M", False),
            (51, ",", False),
            (52, ".", False),
            (53, "/", False),
            (54, "Shift", True),
        ],
        [
            (29, "Ctrl", False),
            (56, "Alt", False),
            (57, "Space", True),
            (100, "Alt", False),
            (97, "Ctrl", False),
            (105, "←", False),
            (103, "↑", False),
            (108, "↓", False),
            (106, "→", False),
        ],
    ],
    "de_CH": [  # Swiss German QWERTZ
        [
            (1, "Esc", True),
            (59, "F1", True),
            (60, "F2", True),
            (61, "F3", True),
            (62, "F4", True),
            (63, "F5", True),
            (64, "F6", True),
            (65, "F7", True),
            (66, "F8", True),
            (67, "F9", True),
            (68, "F10", True),
            (87, "F11", True),
            (88, "F12", True),
        ],
        [
            (41, "§", False),
            (2, "1", False),
            (3, "2", False),
            (4, "3", False),
            (5, "4", False),
            (6, "5", False),
            (7, "6", False),
            (8, "7", False),
            (9, "8", False),
            (10, "9", False),
            (11, "0", False),
            (12, "'", False),
            (13, "^", False),
            (14, "Backspace", True),
        ],
        [
            (15, "Tab", True),
            (16, "Q", False),
            (17, "W", False),
            (18, "E", False),
            (19, "R", False),
            (20, "T", False),
            (21, "Z", False),
            (22, "U", False),
            (23, "I", False),
            (24, "O", False),
            (25, "P", False),
            (26, "ü", False),
            (27, "¨", False),
            (43, "$", True),
        ],
        [
            (58, "Caps", True),
            (30, "A", False),
            (31, "S", False),
            (32, "D", False),
            (33, "F", False),
            (34, "G", False),
            (35, "H", False),
            (36, "J", False),
            (37, "K", False),
            (38, "L", False),
            (39, "ö", False),
            (40, "ä", False),
            (28, "Enter", True),
        ],
        [
            (42, "Shift", False),
            (86, "<", False),
            (44, "Y", False),
            (45, "X", False),
            (46, "C", False),
            (47, "V", False),
            (48, "B", False),
            (49, "N", False),
            (50, "M", False),
            (51, ",", False),
            (52, ".", False),
            (53, "-", False),
            (54, "Shift", True),
        ],
        [
            (29, "Ctrl", False),
            (56, "Alt", False),
            (57, "Space", True),
            (100, "AltGr", False),
            (97, "Ctrl", False),
            (105, "←", False),
            (103, "↑", False),
            (108, "↓", False),
            (106, "→", False),
        ],
    ],
}
