name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    timeout-minutes: 1

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Skip on main branch
        if: github.event_name == 'push'
        run: |
          echo "Skipping spellcheck on main branch - this job exists only for status check requirements"
          exit 0

      - name: Checkout repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Starting cspell
        if: github.event_name == 'pull_request'
        uses: streetsidesoftware/cspell-action@v7
        with:
          files: ""
          root: "."
          check_dot_files: false
          inline: error
          treat_flagged_words_as_errors: false
          suggestions: true
          strict: true
          config: ".cspell.yaml"
          incremental_files_only: ${{ env.ACT != 'true' }}
          verbose: true
          use_cspell_files: false

      - name: Wait 20 seconds
        run: sleep 20
