name: Generate Release Notes
on:
  push:
    tags:
      - "R*" # Trigger on tags such as R1

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Tag Number
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TAG_NUMBER=${TAG_NAME#R}
          echo "tag_number=$TAG_NUMBER" >> $GITHUB_OUTPUT
          echo "full_tag=$TAG_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get Previous Tag
        id: previous_tag
        run: |
          PREV_TAG=$(git tag --sort=-version:refname | grep -A 1 ${GITHUB_REF#refs/tags/} | tail -n 1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Version Environment Variable
        run: |
          echo "TYPETRACE_VERSION=${{ steps.extract_tag.outputs.full_tag }}" >> $GITHUB_ENV

      - name: Install Flatpak and Flatpak-builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder make

      - name: Build and Export Flatpak
        id: build_flatpak
        run: |
          flatpak install -y org.gnome.Sdk//46 org.gnome.Platform//46 # We're using 46 here, since ubuntu doesn't support 48 yet
          make flatpak-export 
          echo "flatpak_file=typetrace.flatpak" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ steps.previous_tag.outputs.prev_tag }}
          toTag: ${{ github.ref_name }}
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.extract_tag.outputs.tag_number }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: ${{ steps.build_flatpak.outputs.flatpak_file }}
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: false
