name: Check Python Code

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install ruff dependencies
        run: uv tool install ruff

      - name: Run ruff
        run: ruff check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: typetrace.flatpak
          manifest-path: edu.ost.typetrace.yaml
          cache-key: flatpak-builder-${{ github.sha }}
