name: Check Python Code

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

permissions:
  pull-requests: write

jobs:
  check-python:
    runs-on: ubuntu-latest

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv and Python
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Display uv cache status
        run: |
          # Color definitions
          RED='\033[1;91m'
          GREEN='\033[1;92m'
          YELLOW='\033[1;93m'
          CYAN='\033[1;96m'
          NC='\033[0m'

          if [[ "${{ steps.setup-uv.outputs.cache-hit }}" == "true" || "${{ steps.setup-uv.outputs.cache-restored }}" == "true" ]]; then
            echo -e "${GREEN}uv cache hit! Using cached dependencies.${NC}"
          else
            echo -e "${YELLOW}uv cache miss. Dependencies will be freshly installed.${NC}"
          fi

      - name: Cache and install APT packages
        id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libdbus-1-dev libgirepository-2.0-0 libgirepository1.0-dev libcairo2-dev
          version: 1.0

      - name: Display APT cache status
        run: |
          # Color definitions
          RED='\033[1;91m'
          GREEN='\033[1;92m'
          YELLOW='\033[1;93m'
          CYAN='\033[1;96m'
          NC='\033[0m'

          if [[ "${{ steps.cache-apt-pkgs.outputs.cache-hit }}" == "true" ]]; then
            echo -e "${GREEN}APT package cache hit! Using cached packages.${NC}"
            echo -e "${CYAN}Installed packages: ${{ steps.cache-apt-pkgs.outputs.package-version-list }}${NC}"
          else
            echo -e "${YELLOW}APT package cache miss. Packages were freshly installed.${NC}"
          fi

      - name: Create virtual environment
        run: uv venv

      - name: Install project dependencies (including dev)
        run: |
          uv lock
          uv sync --frozen --all-extras

      - name: Run ruff
        run: uv run ruff check

      - name: Run tests
        run: |
          uv pip install pytest-cov
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. | tee pytest-coverage.txt

      - name: Add coverage comment to PR
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          title: "TypeTrace Coverage Report"
