name: Spellcheck

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Checks the documents for spelling

    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Starting cspell
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: ""
          root: "."
          check_dot_files: false
          inline: error
          treat_flagged_words_as_errors: false
          suggestions: true
          strict: true
          config: ".github/spellcheck/cspell.json"
          incremental_files_only: false
          verbose: true
          use_cspell_files: false
