name: Auto Update PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

jobs:
  autoupdate:
    runs-on: ubuntu-22.04 # Use the version specified in the action's docs
    name: Auto Update PRs
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action@v1
        id: autoupdate
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use a Personal Access Token
          MERGE_CONFLICT_ACTION: "fail"
          PR_FILTER: "all"
          MERGE_MSG: "Auto-updated PR branch with latest changes from main"
      - name: Log Merge Conflicts
        if: steps.autoupdate.outputs.conflicted == 'true'
        run: echo "Merge conflicts detected in one or more PRs"
      - name: Log Success
        if: steps.autoupdate.outputs.conflicted == 'false'
        run: echo "PRs updated successfully or no updates needed"
