name: Package

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  windows_package:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [ x64, x86 ]
        python: [ "3.10" ]
        libtorrent: [ 2.0.7, 1.2.19 ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout Deluge source to subdir to enable packaging any tag/commit
      - name: Checkout Deluge source
        if: env.ACT != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: deluge_src

      - name: Set up Python
        if: env.ACT != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python}}
          architecture: ${{ matrix.arch }}
          cache: pip

      - name: Prepare pip
        if: env.ACT != 'true'
        run: python -m pip install wheel setuptools==68.*

      - name: Install GTK
        if: env.ACT != 'true'
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://github.com/deluge-torrent/gvsbuild-release/releases/download/latest/gvsbuild-py${{ matrix.python }}-vs16-${{ matrix.arch }}.zip","C:\GTK.zip")
          7z x C:\GTK.zip -oc:\GTK
          echo "C:\GTK\release\lib" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release" | Out-File -FilePath $env:GITHUB_PATH -Append
          python -m pip install --no-index --find-links="C:\GTK\release\python" pycairo PyGObject

      - name: Install Python dependencies
        if: env.ACT != 'true'
        # Pillow no longer provides 32-bit wheels for Windows
        # so specify only-binary to install old version.
        run: pip install -e .

      - name: Install build dependecies
        if: env.ACT != 'true'
        run: pip install -e.[build]

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Build with Meson
        run: |
          meson setup builddir
          meson compile -C builddir
          meson install -C builddir 

      - name: Freeze TypeTrace
        if: env.ACT != 'true'
        run: pyinstaller --clean typetrace.spec --distpath freeze

      - name: Make TypeTrace Installer
        if: env.ACT != 'true'
        run: makensis /Darch=${{ matrix.arch }} typetrace-win-installer.nsi

      - uses: actions/upload-artifact@v4
        with:
          name: typetrace-${{ github.ref_name }}-${{ matrix.arch }}
          path: |
            typetrace-installer.exe
            _install/bin/typetrace  # Falls ihr die rohe Binary auch bereitstellen wollt